---
abstract: 'bindings to the potrace library'
author:
  - 'Flavio Poletti <polettix@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graphics-Potrace
requires:
  Moo: 0.009011
  perl: 5.008_000
version: 0.73
